### PR TITLE
Update module to SS4 conventions

### PR DESCRIPTION
**Pull request by jakxnz**
# Changes

* General modifications to adhere to SS 4 conventions throughout
* Rename OAuth.php to OAuthServerController.php
* Add `$table_name`s to object classes
* Update $indexes to match current spec in ClientEntity.php and ScopeEntity.php
* Use SiteConfig module in place of CMS module
* Use robbie/psr7-adapters in place of iansimpson/psr7
* Update name-spacing for closer PSR-4 compliance
* Add PSR-4 to composer.json
* Refactor to use PSR-2 conventions
* Move extensions config from _config.php to _config/config.yml

---

# Semver
@IanSimpson what do you think about versioning the project? Because the level of integration is still quite light, I thought the versions might be `0.1.x` for `SS 3.6` compatibility and `0.2.x` for `SS 4.x` compatibility?

The project could receive a `1.0` release when it is using `thephpleague/oauth2-server` more comprehensively (middleware), has tests, and has CI and other checks?

Thoughts?

### CODE REVIEW

**Comment by jakxnz** [comment]
https://github.com/IanSimpson/ss-oauth2-server/issues/2

**Comment by spekulatius** [comment]
Hello @jakxnz 

thanks for providing this. I'll check it out and provide you some feedback once I gave it a spin.

Cheers,
Peter

**Comment by IanSimpson** [comment]
Brilliant, thanks. Sorry I missed the notifications about this.

I've made a pre-merge release versioned at 0.1.0 to maintain SS3.6 compatibility, and will use 0.2.x for SS4-compatible. Agree we're certainly not at a 1.0 level yet.

@spekulatius have you had a chance to test this out? Are we ready to make a 0.2.0 release?

**Comment by spekulatius** [comment]
Hello @IanSimpson and @jakxnz 

No, I haven't had a chance. Hopefully getting there shortly. I'll update you once it's done.

Cheers,
Peter

**Pull request merged**
