### PR TITLE
Tidy up - SS3

### PR DESCRIPTION
**Pull request by mateusz**
Hi!

Would you mind having the module cleaned up? See the list of changes below - diff looks scary big, but that's because it's been machine-formatted for PSR-2. Other notable changes include a functional test that covers the controller and then also automatic scrutinizer static analysis (and assorted fixes) and travis (for running the tests on each PR).

Note I've tested on my scrutinizer & travis account, but since this is your module, you would need to enable the integration separately :-) With the config files in place it's pretty easy. See the results here:

 * [scrutinizer](https://scrutinizer-ci.com/g/mateusz/ss-oauth2-server/inspections/0f1817b1-300a-43cf-8fb4-7d6702a81a5d)
* [travis](https://travis-ci.org/mateusz/ss-oauth2-server/builds/437044769)

You can even get yourself a badge and pop it into your REDME ;-)

I've tested this change in a real-life SSO setup, and it works ok. I'll do similar thing to SS4 branch next, if this one looks good to you.

What do you think?

Mateusz

### CODE REVIEW

**Comment by IanSimpson** [comment]
Brilliant. Thanks!

**Comment by mateusz** [comment]
Thanks for merging. You reckon you could flip the travis and scrutinizer integration on? This way they will automatically run on newly submitted PRs so it's visible if PR broke anything, the same like for example [in the Framework PRs](https://github.com/silverstripe/silverstripe-framework/pull/8465) - click "Show all checks" thingie to see what I mean.

If you are not working on this module too heavily, there is also a possibility of adding someone else as a maintainer hint hint wink wink. Completely up to you of course. Looks like we are going to use this quite a bit.

**Comment by IanSimpson** [comment]
I've clicked a big button on Travis and Scrutinizer, so hopefully they're up and running. I've added you and Sean as collaborators too :)

**Comment by mateusz** [comment]
Thanks! Scrutinizer is definitely working "Your code was rated 10 (very good). " Travis needs another merge or push, we'll see then!

**Comment by IanSimpson** [comment]
Lol, I'm not sure it is working if it rates my code a 10...

**Pull request merged**
